name: Build & Test Run

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      build_date: ${{ steps.ts.outputs.DATE }}
      build_type: ${{ steps.ts.outputs.KERNEL_BUILD_TYPE }}
    steps:
      - id: ts
        run: |
          echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
          echo "KERNEL_BUILD_TYPE=Testing" >> $GITHUB_OUTPUT

  # device workflow imports goes in here
  build-lineage-sm6150:
    needs: setup
    uses: ./.github/workflows/lineage-sm6150.yml
    with:
      build_date: ${{ needs.setup.outputs.build_date }}
      build_type: ${{ needs.setup.outputs.build_type }}
    secrets: inherit

  build-lineage-sm6125:
    needs: setup
    uses: ./.github/workflows/lineage-sm6125.yml
    with:
      build_date: ${{ needs.setup.outputs.build_date }}
      build_type: ${{ needs.setup.outputs.build_type }}
    secrets: inherit

  build-crdroid-sm6150:
    needs: setup
    uses: ./.github/workflows/crdroid-sm6150.yml
    with:
      build_date: ${{ needs.setup.outputs.build_date }}
      build_type: ${{ needs.setup.outputs.build_type }}
    secrets: inherit
  
  build-pixelos-sm6150:
    needs: setup
    uses: ./.github/workflows/pixelos-sm6150.yml
    with:
      build_date: ${{ needs.setup.outputs.build_date }}
      build_type: ${{ needs.setup.outputs.build_type }}
    secrets: inherit

  build-awaken-sm6150:
    needs: setup
    uses: ./.github/workflows/awaken-sm6150.yml
    with:
      build_date: ${{ needs.setup.outputs.build_date }}
      build_type: ${{ needs.setup.outputs.build_type }}
    secrets: inherit

  build-mithorium-msm8937:
    needs: setup
    uses: ./.github/workflows/mithorium-msm8937.yml
    with:
      build_date: ${{ needs.setup.outputs.build_date }}
      build_type: ${{ needs.setup.outputs.build_type }}
    secrets: inherit

  build-mititanium-msm8953:
    needs: setup
    uses: ./.github/workflows/mititanium-msm8953.yml
    with:
      build_date: ${{ needs.setup.outputs.build_date }}
      build_type: ${{ needs.setup.outputs.build_type }}
    secrets: inherit
